### ISSUE TITLE
Do not use private repositories for mentoring tasks!

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#1]
https://github.com/vatolinrp/bitcoin-esb/blob/master/gradle.properties#L25
https://github.com/vatolinrp/bitcoin-esb/blob/master/build.gradle#L112

**Comment by vatolinrp** [comment]
I need one or two artifacts from this private repository. I think if I move these artifacts to a repository which has been given to me for mentoring, it would be acceptable in my case.

**Comment by madhead** [comment]
What are that dependencies? Just don't use anything, that is not in Maven Central / jcenter!

**Comment by vatolinrp** [comment]
fixed in commit
757d66c73f13c8c0416bbb216f03817c6c6ae98b

**Comment by madhead** [comment]
I don't believe this artifacts do not exist in jcenter or maven central.

**Comment by vatolinrp** [comment]
In maven repo there is a link to a repo which I defined in the properties
https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-frontend-jaxws/3.0.4.redhat-621084
jcenter does not have this artifact
https://bintray.com/bintray/jcenter/org.apache.cxf%3Acxf-rt-frontend-jaxws
Did I miss something?

**Comment by madhead** [comment]
Of cource neither JCenter nor Maven central do not contain those repacked artifacts. They [have](https://bintray.com/bintray/jcenter/org.apache.cxf%3Acxf-rt-frontend-jaxws/3.0.4) the original one that you should use. Replace that repo with `jcenter()` and do not use any proprietary shit for mentoring.

**Comment by vatolinrp** [comment]
Agree, I was doing not the right thing. Thanks
Fixed here
cd3ba95bf8e3faca03eb9b776b5e55f8653909d0

**Comment by vatolinrp** [comment]
Is there anything I missed? Could this issue be closed?
