### ISSUE TITLE
Use osgi plugin

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#10]
Why didn't you use Gradle's OSGi plugin and populate manifests by hands in all the projects?

**Comment by vatolinrp** [comment]
Here is where I define osgi gradle plugin
https://github.com/vatolinrp/bitcoin-esb/blob/master/build.gradle#L83

**Comment by madhead** [comment]
You still configure manifest entries manually.

**Comment by vatolinrp** [comment]
Thanks, I read gradle osgi plugin doc one more time and made some updates
38dd0637fcfd3cb4df58bd645ae1e9c17335be29
I left somewhere `Import-Package` settings remaining since they are used in spring context xml configuration.

**Comment by madhead** [comment]
That's ok
