### ISSUE TITLE
Poor design

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#11]
This class is poorly designed.

https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/bitcoin-model/src/main/java/com/vatolinrp/bitcoin/model/BitcoinPriceValues.java#L7

Imagine, you want to add support for more and more currencies. It will require adding more and more fields, getters and setters. Why did you choose this design?

You can parse blockchain.info responses into Map.

**Comment by vatolinrp** [comment]
Thanks,
77c1dee6021d2eeddb05f6e4f75e596479fc023b

**Comment by vatolinrp** [comment]
Thanks, now I return an object containing a list in soap service and an object containing a map in rest service, where key is a currency code. I think this issue could be closed.
