### ISSUE TITLE
Why "ru" in the URL?

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#12]
https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/bitcoin-common/src/main/resources/conf/base.properties#L1

**Comment by vatolinrp** [comment]
Thanks, this is not necessary
Fixed in this commit
853cac611a2233c275d02d4482d4019fbf890af0
