### ISSUE TITLE
Use Wiremock for this test

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#14]
https://github.com/vatolinrp/bitcoin-esb/blob/a25aaba369925cfda15c71052b1120838758955e/bitcoin-common/src/test/java/com/vatolinrp/bitcoin/dao/PriceDAOImplTest.java#L16

**Comment by vatolinrp** [comment]
I decided to cover dao logic with unit tests and use wiremock for functional tests.
https://github.com/vatolinrp/bitcoin-esb/tree/master/bitcoin-functional-tests
How do you feel about it?
