### ISSUE TITLE
common module is dao / service module

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#15]
Common module does not contain any other classes except DAOs. BTW, that DAOs are actually services. Why it's name is common?

**Comment by vatolinrp** [comment]
These DAOs classes are used in other modules, so they are common. I agree, that calling this module as dao module will be also a good idea.

**Comment by vatolinrp** [comment]
I decided that calling this module as dao module would be a better idea
d1e1811007e85a22e7f41efb79e8cd4e4d1e6016
