### ISSUE TITLE
These lines seem to be redundant

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#16]
`plugins` block should not require any repositories.

https://github.com/vatolinrp/bitcoin-esb/blob/4beacd4343aa46535565cac0a304d19ac6456f7d/bitcoin-wsdl/build.gradle#L1-L10

**Comment by vatolinrp** [comment]
Thanks,
Fixed in commit
a0ef1bca3cd01608a488f10d61e34e27d4d75671

**Comment by vatolinrp** [comment]
Could you close this issue if you have no more questions. Thanks.
