### ISSUE TITLE
What is the difference between int and func tests?

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#17]

**Comment by vatolinrp** [comment]
In my view, func tests are aimed at logic which does not work with external systems or services. Int tests, on the other hand, test the basic integration work because they don't want to test services or systems with which main application integrates.

**Comment by madhead** [comment]
But both tests are very similar in this repo, aren't they?

**Comment by vatolinrp** [comment]
Agree, will make func tests run with wiremock.

**Comment by vatolinrp** [comment]
My Integration tests check happy path by calling real service
https://github.com/vatolinrp/bitcoin-esb/tree/master/bitcoin-integration-tests
And in my functional tests I mocked the external service and checked different scenarios 
https://github.com/vatolinrp/bitcoin-esb/tree/master/bitcoin-functional-tests
I think this is a good approach. What do you think?

**Comment by vatolinrp** [comment]
Could this issue be closed?

**Comment by vatolinrp** [comment]
Do I need to add something here?
