### ISSUE TITLE
Do not expose infrastructure details in project

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#5]
https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/gradle.properties#L24

**Comment by vatolinrp** [comment]
Do you mean I should avoid setting values of systemProp in properties file or I should not keep details like hostname in this place? It is not clear for me.

**Comment by madhead** [comment]
Any place is good unless it is not exposed. As long as you're using Jenkins to build the app (which is not public, I hope), you can use Jenkins to store that data as environment variables for a job (or globally).

**Comment by vatolinrp** [comment]
Thanks, got it.

**Comment by vatolinrp** [comment]
Fixed
0fe557f467a2b89558687939f515250e65d28ba7

**Comment by vatolinrp** [comment]
can this issue be closed?
