### ISSUE TITLE
Why do you publish all commits?

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#8]
https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/Jenkinsfile#L18-L20

**Comment by vatolinrp** [comment]
I see nothing bad when any of my snapshot commit is published. You think it is a bad practice to do that?

**Comment by madhead** [comment]
Yes, it's very bad.

Imagine, you and and your teammates are working on three features simultaneously. You do your work in branches. In three different branches, forked from master `1.0.0-SNAPSHOT`. You all push your branches in Git and they are built by Jenkins.

Question: what is a `1.0.0-SNAPSHOT` in the artifactory? What branch does it correspond? How do you tell?

**Comment by vatolinrp** [comment]
Agree, this would be confusing. I'm thinking of adding the name of current branch (if it is not master) to jar file and then do the upload to artifactory. I think it would be better than just a skip of all snapshot versions. How do you feel about this approach?

**Comment by vatolinrp** [comment]
Fixed.
649f8c005f3511bfd6306cb81e204ba4e1ec56ac
Is it possible to close this issue?
