### ISSUE TITLE
Simplify the logic

### ISSUE THREAD

**Issue by madhead** [vatolinrp/bitcoin-esb#9]
I see you first read the reponse into a string and later parse it into an objec:

https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/bitcoin-common/src/main/java/com/vatolinrp/bitcoin/dao/PriceDAOImpl.java#L56
https://github.com/vatolinrp/bitcoin-esb/blob/22ac104cbcbc979f6d5a042fdc765d5008de9109/bitcoin-common/src/main/java/com/vatolinrp/bitcoin/dao/PriceDAOImpl.java#L46

As far as I remember `RestTemplate` can parse JSONs automatically.

**Comment by vatolinrp** [comment]
Updated here,
77c1dee6021d2eeddb05f6e4f75e596479fc023b

**Comment by vatolinrp** [comment]
Now I read response into a Map. What do you think about my change?
